name: Generate Snake Game from GitHub Contribution Grid

on:
  workflow_dispatch:

jobs:
  generate_snake:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake Game
        uses: Platane/snk@v3.2.0
